spring.application.name=demo-docker
server.port=${PORT:8080}
server.address=0.0.0.0

management.info.env.enabled=true
info.app.name=DockerDemo
info.app.version=1.0.0
info.app.description=Docker minimal config

management.endpoints.web.exposure.include=health,info
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
